triviacountry_pages = [
'http://www.triviacountry.com/274-Animal-trivia.htm',
'http://www.triviacountry.com/275-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/276-fun-animal-trivia.htm',
'http://www.triviacountry.com/277-Trivia-Animal.htm',
'http://www.triviacountry.com/278-Trivia-Questions-Animals.htm',
'http://www.triviacountry.com/279-Animal-fun-trivia-questions.htm',
'http://www.triviacountry.com/280-Trivia-Animal-questions.htm',
'http://www.triviacountry.com/281-Animal-Trivia-Interesting.htm',
'http://www.triviacountry.com/282-Cool-Animal-Trivia.htm',
'http://www.triviacountry.com/283-Animal-trivia-questions.htm',
'http://www.triviacountry.com/154-History-trivia.htm',
'http://www.triviacountry.com/155-Historical-trivia.htm',
'http://www.triviacountry.com/304-American-History-Trivia.htm',
'http://www.triviacountry.com/303-world-history-trivia.htm',
'http://www.triviacountry.com/306-History-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/307-Miscellaneous-American-History-Trivia.htm',
'http://www.triviacountry.com/308-Trivia-Quiz-Questions-History.htm',
'http://www.triviacountry.com/296-World-trivia-history-quiz.htm',
'http://www.triviacountry.com/297-history-world-trivia-questions.htm',
'http://www.triviacountry.com/298-Trivia-questions-world-history.htm',
'http://www.triviacountry.com/23_American_Trivia.htm',
'http://www.triviacountry.com/24_American.htm',
# 'http://www.triviacountry.com/25_American.htm',
# 'http://www.triviacountry.com/26_American.htm',
# 'http://www.triviacountry.com/27_America.htm',
# 'http://www.triviacountry.com/28_America.htm',
'http://www.triviacountry.com/29_America.htm',
'http://www.triviacountry.com/01_Arts_Trivia.htm',
'http://www.triviacountry.com/02_Arts.htm',
'http://www.triviacountry.com/03_Arts.htm',
'http://www.triviacountry.com/04_Arts.htm',
'http://www.triviacountry.com/05_Arts.htm',
'http://www.triviacountry.com/06_Arts.htm',
'http://www.triviacountry.com/196-Artists-arts-trivia.htm',
'http://www.triviacountry.com/188-Stage-plays.htm',
'http://www.triviacountry.com/172-Entertainment-trivia.htm',
'http://www.triviacountry.com/189-On-Stage.htm',
'http://www.triviacountry.com/177-cinema-TV.htm',
'http://www.triviacountry.com/179-TV-cinema.htm',
'http://www.triviacountry.com/63_movies.htm',
'http://www.triviacountry.com/64_movies.htm',
'http://www.triviacountry.com/65_movies.htm',
'http://www.triviacountry.com/66_movies.htm',
'http://www.triviacountry.com/121-movies.htm',
'http://www.triviacountry.com/122-movies.htm',
'http://www.triviacountry.com/126-trivia-movies.htm',
'http://www.triviacountry.com/178-TV-Movies.htm',
'http://www.triviacountry.com/73_television.htm',
'http://www.triviacountry.com/14_TV_Trivia.htm',
'http://www.triviacountry.com/14_TV_Trivia.htm',
'http://www.triviacountry.com/15_TV.htm',
'http://www.triviacountry.com/74_TV.htm',
'http://www.triviacountry.com/75_TV.htm',
'http://www.triviacountry.com/114-trivia.htm',
'http://www.triviacountry.com/124-trivia-TV.htm',
'http://www.triviacountry.com/13_movies_Trivia.htm',
'http://www.triviacountry.com/63_movies.htm',
'http://www.triviacountry.com/64_movies.htm',
# 'http://www.triviacountry.com/65_movies.htm',
# 'http://www.triviacountry.com/66_movies.htm',
# 'http://www.triviacountry.com/121-movies.htm',
'http://www.triviacountry.com/122-trivia-movies-oscars.htm',
'http://www.triviacountry.com/126-trivia-movies.htm',
'http://www.triviacountry.com/178-TV-Movies.htm',
'http://www.triviacountry.com/30_Business_Trivia.htm',
'http://www.triviacountry.com/31_Business.htm',
'http://www.triviacountry.com/32_Business.htm',
'http://www.triviacountry.com/32_Business.htm',
'http://www.triviacountry.com/33_Business.htm',
'http://www.triviacountry.com/34_Business.htm',
'http://www.triviacountry.com/288-Cartoon-trivia.htm',
'http://www.triviacountry.com/289-Comic-Cartoon-Trivia.htm',
'http://www.triviacountry.com/290-Trivia-cartoons-comics.htm',
'http://www.triviacountry.com/332-Dance-Trivia-questions.htm',
'http://www.triviacountry.com/333-Trivia-Questions-Dance.htm',
'http://www.triviacountry.com/334-Dance-trivia-Questions-Answers.htm',
'http://www.triviacountry.com/205-Easy-Trivia-miscellaneous.htm',
'http://www.triviacountry.com/206-Printable-Trivia-random.htm',
'http://www.triviacountry.com/207-Free-Easy-Trivia-Questions-and-Answers.htm',
'http://www.triviacountry.com/208-Free-Easy-Printable-Trivia-Questions-and-Quizzes-With-Answers.htm',
'http://www.triviacountry.com/209-Trivia-Questions-and-Quizzes-With-Answers.htm',
'http://www.triviacountry.com/210-Free-Easy-Trivia-Questions-and-Answers.htm',
'http://www.triviacountry.com/211-Easy-Trivia-Questions-With-Answers.htm',
'http://www.triviacountry.com/212-Easy-Trivia.htm',
'http://www.triviacountry.com/213-Easy-Trivia.htm',
# 'http://www.triviacountry.com/214-Easy-Trivia-Questions.htm',
# 'http://www.triviacountry.com/238-Easy-Famous-People.htm',
'http://www.triviacountry.com/240-Famous-People-Trivia-Questions-easy.htm',
'http://www.triviacountry.com/241-Famous-People-Trivia-Easy.htm',
'http://www.triviacountry.com/242-Easy-Trivia-Questions.htm',
'http://www.triviacountry.com/12_Food_Trivia.htm',
'http://www.triviacountry.com/37_Food.htm',
'http://www.triviacountry.com/38_Food.htm',
'http://www.triviacountry.com/39_Food.htm',
'http://www.triviacountry.com/40_Food.htm',
'http://www.triviacountry.com/41_Food.htm',
'http://www.triviacountry.com/42_Food.htm',
'http://www.triviacountry.com/184-food-drink.htm',
'http://www.triviacountry.com/362-food-trivia.htm',
'http://www.triviacountry.com/362-food-trivia.htm',
'http://www.triviacountry.com/363-food-trivia-quiz.htm',
'http://www.triviacountry.com/364-international-food-trivia.htm',
'http://www.triviacountry.com/365-food-trivia-questions.htm',
'http://www.triviacountry.com/366-Trivia-questions-answers.htm',
'http://www.triviacountry.com/361-cocktails-beverages-trivia.htm',
'http://www.triviacountry.com/361-drinks-cocktails-trivia.htm',
'http://www.triviacountry.com/266-funny-trivia-questions.htm',
'http://www.triviacountry.com/267-Trivia-questions-funny.htm',
'http://www.triviacountry.com/268-Trivia-funny-questions.htm',
'http://www.triviacountry.com/269-Trivia-Quiz-Funny.htm',
'http://www.triviacountry.com/270-hilarious-trivia-questions-answers.htm',
'http://www.triviacountry.com/171-general-knowledge-trivia.htm',
'http://www.triviacountry.com/200-general-knowledge-trivia.htm',
'http://www.triviacountry.com/224-General-Knowledge-Random-Trivia.htm',
'http://www.triviacountry.com/225-General-Knowledge-Trivia.htm',
'http://www.triviacountry.com/226-Trivia-General-Knowledge-Quiz.htm',
'http://www.triviacountry.com/227-General-Knowledge-Trivia-Quiz-Questions.htm',
'http://www.triviacountry.com/228-Trivia-Quiz-Questions-General-Knowledge.htm',
'http://www.triviacountry.com/229-Trivia.htm',
'http://www.triviacountry.com/230-Questions-Trivia-General-Knowledge.htm',
'http://www.triviacountry.com/231-Trivia-Questions-Answers-Random-Miscelaneous.htm',
'http://www.triviacountry.com/232-General-Knowledge-Trivia-Quesions.htm',
'http://www.triviacountry.com/233-General-knowledge-trivia.htm',
'http://www.triviacountry.com/234-Trivia-Questions-Answers-General.htm',
'http://www.triviacountry.com/235-general-knowledge-trivia-and-answers.htm',
'http://www.triviacountry.com/106-hard-trivia-questions.htm',
# 'http://www.triviacountry.com/107-hard-trivia.htm',
# 'http://www.triviacountry.com/108-hard-questions.htm',
# 'http://www.triviacountry.com/109-hard-trivia-questions.htm',
# 'http://www.triviacountry.com/109-hard-trivia-questions.htm',
# 'http://www.triviacountry.com/110-hard-questions.htm',
'http://www.triviacountry.com/111-trivia-questions.htm',
'http://www.triviacountry.com/112-trivia-questions-answers.htm',
'http://www.triviacountry.com/113-questions-answers.htm',
'http://www.triviacountry.com/134-questions-answers-trivia.htm',
'http://www.triviacountry.com/135-Harder-questions-trivia.htm',
'http://www.triviacountry.com/236-hard-trivia-questions.htm',
'http://www.triviacountry.com/237-Harder-trivia-questions.htm',
'http://www.triviacountry.com/299-World-history-quiz-questions.htm',
'http://www.triviacountry.com/300-World-history-trivia-answers.htm',
'http://www.triviacountry.com/301-Trivia-history-questions.htm',
'http://www.triviacountry.com/302-history-world-quiz.htm',
'http://www.triviacountry.com/291-International-trivia-questions.htm',
'http://www.triviacountry.com/292-International-Trivia-Questions.htm',
'http://www.triviacountry.com/293-Trivia-Questions-International.htm',
'http://www.triviacountry.com/294-Trivia-International.htm',
'http://www.triviacountry.com/295-International-Trivia-Questions.htm',
'http://www.triviacountry.com/35_invention_Trivia.htm',
'http://www.triviacountry.com/36_invention.htm',
'http://www.triviacountry.com/271-inventions-trivia-questions.htm',
'http://www.triviacountry.com/272-Trivia-questions-inventions.htm',
'http://www.triviacountry.com/273-inventors-trivia-questions.htm',
'http://www.triviacountry.com/Trivia-For-Kids.htm',
'http://www.triviacountry.com/Free-Printable-Kids-Triva.htm',
'http://www.triviacountry.com/Kids-Trivia.htm',
'http://www.triviacountry.com/21_Language_Trivia.htm',
'http://www.triviacountry.com/43_Language.htm',
'http://www.triviacountry.com/44_Language.htm',
'http://www.triviacountry.com/45_Language.htm',
'http://www.triviacountry.com/46_Language.htm',
'http://www.triviacountry.com/47_Language.htm',
'http://www.triviacountry.com/48_Language.htm',
'http://www.triviacountry.com/49_Language.htm',
'http://www.triviacountry.com/50_Language.htm',
'http://www.triviacountry.com/335-stupid-legal-trivia.htm',
'http://www.triviacountry.com/336-legal-trivia-questions.htm',
'http://www.triviacountry.com/337-illegal-trivia-questions.htm',
'http://www.triviacountry.com/338-legal-trivia-questions.htm',
'http://www.triviacountry.com/339-trivia-questions-legal.htm',
'http://www.triviacountry.com/193-literature-trivia.htm',
'http://www.triviacountry.com/193-literature-trivia.htm',
'http://www.triviacountry.com/195-literature-Quiz-trivia.htm',
'http://www.triviacountry.com/194-literature-trivia-Quiz.htm',
'http://www.triviacountry.com/340-literature-trivia-question.htm',
'http://www.triviacountry.com/341-novels-trivia-questions.htm',
'http://www.triviacountry.com/342-trivia-quiz-questions-literature.htm',
'http://www.triviacountry.com/343-authors-trivia-questions.htm',
'http://www.triviacountry.com/17_Medicine_Trivia.htm',
'http://www.triviacountry.com/56_Medicine.htm',
'http://www.triviacountry.com/57_Medicine.htm',
'http://www.triviacountry.com/163-human-body-science.htm',
'http://www.triviacountry.com/164-human-body-trivia.htm',
'http://www.triviacountry.com/284-Medical-Trivia-Questions.htm',
'http://www.triviacountry.com/285-medical-trivia-q-a.htm',
'http://www.triviacountry.com/286-Questions-Trivia-Medical-Health.htm',
'http://www.triviacountry.com/287-Trivia-Questions-Answers-Medical.htm',
'http://www.triviacountry.com/368-medicine-trivia.htm',
'http://www.triviacountry.com/19_Military_Trivia.htm',
'http://www.triviacountry.com/19_Military_Trivia.htm',
# 'http://www.triviacountry.com/97_military.htm',
# 'http://www.triviacountry.com/98_military.htm',
# 'http://www.triviacountry.com/99_military.htm',
'http://www.triviacountry.com/216-War-Military-Trivia.htm',
'http://www.triviacountry.com/91_miscellaneous_Trivia.htm',
'http://www.triviacountry.com/92_miscellaneous.htm',
'http://www.triviacountry.com/93_miscellaneous.htm',
'http://www.triviacountry.com/94_misc.htm',
'http://www.triviacountry.com/95_misc.htm',
'http://www.triviacountry.com/136-questions.htm',
'http://www.triviacountry.com/143-%20Trivia-Quiz-Questions.htm',
# 'http://www.triviacountry.com/150-Miscellaneous-trivia.htm',
# 'http://www.triviacountry.com/128-pot-luck-trivia.htm',
'http://www.triviacountry.com/130-trivia-miscellaneous-potluck.htm',
'http://www.triviacountry.com/131-trivia-random-potluck.htm',
'http://www.triviacountry.com/142-Trivia-Questions.htm',
'http://www.triviacountry.com/127-pot-luck.htm',
'http://www.triviacountry.com/100-trivia-misc.htm',
'http://www.triviacountry.com/101-miscellaneous-random-trivia.htm',
'http://www.triviacountry.com/102--random-Random-trivia.htm',
'http://www.triviacountry.com/103-Random-trivia.htm',
# 'http://www.triviacountry.com/104-Random-trivia-questions.htm',
# 'http://www.triviacountry.com/105-Random-trivia-questions.htm',
'http://www.triviacountry.com/199-Technology-trivia.htm',
'http://www.triviacountry.com/144-%20Trivia-Quiz-Questions-old-news.htm',
'http://www.triviacountry.com/198-buildings-trivia.htm',
'http://www.triviacountry.com/120-easy-internet.htm',
'http://www.triviacountry.com/141-famous-names.htm',
'http://www.triviacountry.com/199-Technology-trivia.htm',
'http://www.triviacountry.com/369-industrial-commercial-trivia.htm',
'http://www.triviacountry.com/309-Old-Movie-Trivia.htm',
'http://www.triviacountry.com/310-movie-trivia-questions.htm',
'http://www.triviacountry.com/311-Trivia-questions-movie.htm',
'http://www.triviacountry.com/312-film-movie-trivia.htm',
'http://www.triviacountry.com/313-old-movie-trivia.htm',
'http://www.triviacountry.com/314-movie-actor-actress-trivia.htm',
'http://www.triviacountry.com/315-Trivia-movies-oscars.htm',
'http://www.triviacountry.com/316-movie-trivia-printable.htm',
'http://www.triviacountry.com/317-movie-trivia-questions-answers.htm',
'http://www.triviacountry.com/318-family-trivia-fun-movie.htm',
'http://www.triviacountry.com/319-actors-movie-trivia.htm',
# 'http://www.triviacountry.com/320-free-trivia-movies.htm',
# 'http://www.triviacountry.com/321-questions-trivia-movies.htm',
'http://www.triviacountry.com/322-old-movie-trivia.htm',
'http://www.triviacountry.com/323-movie-trivia-answers.htm',
'http://www.triviacountry.com/51_Music.htm',
'http://www.triviacountry.com/52_Music.htm',
'http://www.triviacountry.com/53_Music.htm',
'http://www.triviacountry.com/54_Music.htm',
'http://www.triviacountry.com/55_Music.htm',
'http://www.triviacountry.com/173-music-trivia.htm',
'http://www.triviacountry.com/174-music-trivia-questions.htm',
'http://www.triviacountry.com/175-jazz-popular-music.htm',
'http://www.triviacountry.com/176-popular-music-instruments.htm',
'http://www.triviacountry.com/139-musicals-trivia.htm',
'http://www.triviacountry.com/358-old-music-trivia.htm',
'http://www.triviacountry.com/359-old-music-trivia.htm',
'http://www.triviacountry.com/360-music-old-trivia.htm',
'http://www.triviacountry.com/09_Mythology.htm',
'http://www.triviacountry.com/190-Mythology-Myths.htm',
'http://www.triviacountry.com/191-Myths-fables.htm',
'http://www.triviacountry.com/18_Nature_Trivia.htm',
'http://www.triviacountry.com/58_Nature.htm',
'http://www.triviacountry.com/59_Nature.htm',
'http://www.triviacountry.com/61_Nature.htm',
'http://www.triviacountry.com/165-nature-earth-trivia.htm',
'http://www.triviacountry.com/166-nature-environmental-trivia.htm',
'http://www.triviacountry.com/167-earth-environmental-trivia.htm',
'http://www.triviacountry.com/123-trivial-people.htm',
'http://www.triviacountry.com/125-trivia-people.htm',
'http://www.triviacountry.com/137-famous-people.htm',
'http://www.triviacountry.com/138-people-trivia-famous.htm',
'http://www.triviacountry.com/158-People-trivia-questions.htm',
'http://www.triviacountry.com/187-people-famous.htm',
'http://www.triviacountry.com/243-Famous-People-Trivia.htm',
# 'http://www.triviacountry.com/244-famous-people-trivia-quiz-questions.htm',
# 'http://www.triviacountry.com/245-Trivia-Famous-People.htm',
'http://www.triviacountry.com/246-Free-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/247-Trivia-Questions-answers-people.htm',
'http://www.triviacountry.com/248-famous-women-men.htm',
'http://www.triviacountry.com/249-People-of-fame-trivia.htm',
'http://www.triviacountry.com/250-trivia-famous-people.htm',
'http://www.triviacountry.com/251-Trivia-Questions-People.htm',
'http://www.triviacountry.com/252-Trivia-Questions-people.htm',
'http://www.triviacountry.com/253-People-Famous-Trivia.htm',
'http://www.triviacountry.com/254-People-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/255-Trivia-Questions-People.htm',
'http://www.triviacountry.com/256-More-Trivia-People.htm',
'http://www.triviacountry.com/257-People-Trivia.htm',
'http://www.triviacountry.com/258-People-Trivia-Questions.htm',
'http://www.triviacountry.com/259-People-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/260-Trivia-Quiz-People.htm',
'http://www.triviacountry.com/261-Trivia-Quiz-Questions-People.htm',
'http://www.triviacountry.com/262-Trivia-Quiz-Questions-People.htm',
# 'http://www.triviacountry.com/220-Cities-States-Trivia.htm',
# 'http://www.triviacountry.com/221-States-Cities-Places-Trivia.htm',
'http://www.triviacountry.com/222-City-State-Trivia-Questions.htm',
'http://www.triviacountry.com/223-cities-states-trivia.htm',
'http://www.triviacountry.com/156-Politics-trivia.htm',
'http://www.triviacountry.com/157-Political-trivia-questions.htm',
'http://www.triviacountry.com/22_Presidential_Trivia.htm',
'http://www.triviacountry.com/67_Presidential.htm',
'http://www.triviacountry.com/68_Presidential.htm',
'http://www.triviacountry.com/69_Presidential.htm',
'http://www.triviacountry.com/70_Presidential.htm',
# 'http://www.triviacountry.com/71_Presidential.htm',
'http://www.triviacountry.com/72_Presidential.htm',
'http://www.triviacountry.com/215-President-Trivia.htm',
'http://www.triviacountry.com/371-American-trivia-questions.htm',
'http://www.triviacountry.com/372-American-trivia-quiz.htm',
'http://www.triviacountry.com/373-trivia-About-america.htm',
'http://www.triviacountry.com/374-trivia-quiz-america.htm',
'http://www.triviacountry.com/375-american-trivia-questions.htm',
'http://www.triviacountry.com/16_Science_Trivia.htm',
'http://www.triviacountry.com/60_Science.htm',
'http://www.triviacountry.com/62_Science.htm',
'http://www.triviacountry.com/159-science-trivia-questions.htm',
'http://www.triviacountry.com/180-general-science.htm',
'http://www.triviacountry.com/181-science-trivia.htm',
'http://www.triviacountry.com/182-science-questions.htm',
'http://www.triviacountry.com/183-trivia-questions.htm',
'http://www.triviacountry.com/183-trivia-questions.htm',
'http://www.triviacountry.com/161-science-animals-plants.htm',
'http://www.triviacountry.com/162-animal-plant-science.htm',
'http://www.triviacountry.com/160-science-trivia-physics.htm',
'http://www.triviacountry.com/168-space-trivia.htm',
'http://www.triviacountry.com/169-space-science.htm',
'http://www.triviacountry.com/170-space-science-trivia.htm',
# 'http://www.triviacountry.com/10_Sports.htm',
# 'http://www.triviacountry.com/11_Sports.htm',
'http://www.triviacountry.com/80_baseball.htm',
'http://www.triviacountry.com/82_Tennis.htm',
'http://www.triviacountry.com/83_Basketball.htm',
'http://www.triviacountry.com/84_Golf.htm',
'http://www.triviacountry.com/85_racing.htm',
'http://www.triviacountry.com/86_Olypmpic.htm',
'http://www.triviacountry.com/87_Boxing.htm',
'http://www.triviacountry.com/88_swimming.htm',
'http://www.triviacountry.com/89_hockey.htm',
'http://www.triviacountry.com/90_bsbll.htm',
'http://www.triviacountry.com/116-sports-trivia-quiz.htm',
'http://www.triviacountry.com/117-sports-questions.htm',
'http://www.triviacountry.com/118-trivia-sports.htm',
'http://www.triviacountry.com/119--sports-questions.htm',
'http://www.triviacountry.com/201-printable-sports-Trivia.htm',
'http://www.triviacountry.com/202-printable-miscellaneous-sports-Trivia.htm',
'http://www.triviacountry.com/203-printable-miscellaneous-sports-Trivia.htm',
'http://www.triviacountry.com/204-printable-random-sports-Trivia.htm',
'http://www.triviacountry.com/217-sports-Trivia.htm',
'http://www.triviacountry.com/218-Random-Sports-Trivia.htm',
'http://www.triviacountry.com/219-Sports-Trivia-Quiz-Questions.htm',
'http://www.triviacountry.com/350-International-Sports-Trivia.htm',
'http://www.triviacountry.com/351-sports-trivia-international.htm',
'http://www.triviacountry.com/352-Trivia-questions-international.htm',
'http://www.triviacountry.com/353-international-sports-quiz.htm',
'http://www.triviacountry.com/354-international-sports-quiz-questions.htm',
'http://www.triviacountry.com/355-sports-trivia-questions.htm',
# 'http://www.triviacountry.com/356-miscellaneous-sports-trivia.htm',
# 'http://www.triviacountry.com/357-sports-trivia-questions.htm',
# 'http://www.triviacountry.com/367-sports-trivia-questions.htm',
'http://www.triviacountry.com/324-Old-TV-Show-Trivia.htm',
'http://www.triviacountry.com/325-TV-trivia-questions.htm',
'http://www.triviacountry.com/326-trivia-questions-TV.htm',
'http://www.triviacountry.com/327-trivia-TV-questions.htm',
'http://www.triviacountry.com/328-TV-Trivia-Questions-Answers.htm',
'http://www.triviacountry.com/329-Trivia-Quiz-Questions-TV.htm',
'http://www.triviacountry.com/330-fun-tv-trivia-questions.htm',
'http://www.triviacountry.com/331-TV-trivia-answers.htm',
'http://www.triviacountry.com/145-%20US-Trivia.htm',
'http://www.triviacountry.com/147-%20US-Trivia-questions.htm',
'http://www.triviacountry.com/345-words-trivia-quiz.htm',
'http://www.triviacountry.com/346-words-trivia-questions.htm',
'http://www.triviacountry.com/347-interesting-words-trivia.htm',
# 'http://www.triviacountry.com/348-trivia-question-word.htm',
# 'http://www.triviacountry.com/349-Words-trivia-questions.htm',
'http://www.triviacountry.com/76_World.htm',
'http://www.triviacountry.com/20_World_Trivia.htm',
'http://www.triviacountry.com/76_World.htm',
'http://www.triviacountry.com/77_World.htm',
'http://www.triviacountry.com/78_World.htm',
'http://www.triviacountry.com/79_international.htm',
'http://www.triviacountry.com/197-UK-trivia-quiz.htm',
'http://www.triviacountry.com/100-Africa-trivia.htm',
'http://www.triviacountry.com/151-Africa-trivia.htm',
'http://www.triviacountry.com/152-Asia-trivia.htm',
'http://www.triviacountry.com/140-europe-trivia.htm',
'http://www.triviacountry.com/153-Europe-trivia.htm',
'http://www.triviacountry.com/149-Miscellaneous-European.htm'
]

triviacountry_pages.each do |page|
  TriviaFactSeeder.new(page).create_stack
end

